Security/Guidelines/Key_Management.mediawiki
Security/Guidelines/OpenSSH.mediawiki

Reported by email by Owen Marshall (thx!)

Remove KeyRegenerationInterval

---

Security/InfoSec.mediawiki

Add Pentesting to Service Catalog

Add Pentesting to Service Catalog

---

Security/InfoSec.mediawiki

Adding Vulnerability Assessment (VA) to the service catalog.

Add vulnerability assessment

---

Security/InfoSec.mediawiki

Pointing VA and PT component bugs to me by default to help with process definition, consistency, and training of other team members.

Make claudijd PoC for VA/PT reviews

---

Security/Guidelines/OpenSSH.mediawiki

need review from @claudijd  @ameihm0912 (this affects the infrasec account though its already setup in a similar way) @bhourigan

Add information about machine accounts w/match and 2FA, sftp logging, and MFA w/ newer OpenSSH

---

Security/Guidelines/Web_Security.mediawiki

- Show deprecation of XXSSP
- Show slower deprecation of XFO
- More examples for XFO and CSP
- Give useful CSP header for APIs

Updates to CSP, XFO, and XXSSP

---

Security.mediawiki

Add Security.mediawiki under version control

---

Security/Guidelines/Web_Security.mediawiki

Fix: irc-contacts for contribute.json formatting.(Clouserw)
Misc spelling/wording (jbryner)

Wiki ports to Git:

---

Security/Guidelines/Web_Security.mediawiki

Note that I am merging this myself, since it has received multiple r+ on IRC.

Add section on refererrrrerrr policy

---

Security/Guidelines/Web_Security.mediawiki

@kangsterizer, could I get some r+ please?  :)

Updates to documentation on referrer policy and XFO

---

Security/Guidelines/Web_Security.mediawiki

Fix typos in Web Security contribute.json Guidelines

---

Security/Guidelines/OpenID_connect.mediawiki

This is a port from https://wiki.mozilla.org/User:Gdestuynder/test/OpenID_Connect_Guide with modifications
I plan to add a technical login flow as well in an upcoming PR.
Actual implementations such as code, configurations, etc. are (or are to be) on https://github.com/mozilla-iam/testrp.security.allizom.org/

Initial version

---

Security/Guidelines/Web_Security.mediawiki
sync.py

Two years was decided between @lgarron, myself, and a bunch of random web sec folks.

Fix sync.py and update HSTS recommendations to two years

---

File/Authentication_Sequence_with_OpenID_Connect.txt
File/README.md

These are not yet automatically synchronized.

Adding a space to store wikimo attachements.

---

Security/Fundamentals/Security_Principles.mediawiki

Several changes/rewording and new section added

version 2.0 / with Gene review

---

Security/Guidelines/OpenSSH.mediawiki

See also: https://github.com/mozilla/wikimo_content/pull/76

Remove "does not include" for conciseness

---

Security/Guidelines/OpenSSH.mediawiki

Make it clear there can be other file names, add some more examples

Fix https://github.com/mozilla/wikimo_content/issues/103

---

Security/Guidelines/OpenSSH.mediawiki

Added a missing s: “this guid show**s** …”

Fixed a tiny typo

---

IAM/Frequently_asked_questions.mediawiki

Live preview: https://wiki.mozilla.org/User:Gdestuynder/faq
This FAQ is necessary in order the enable this in production IAM:
- GitHub MFA enforcement
- LDAP MFA enforcement
- Account upgrades (this one also require additional communication to specific groups)

Initial commit of IAM public FAQ

---

IAM/Frequently_asked_questions.mediawiki

Fix typos.

---

IAM/Frequently_asked_questions.mediawiki

Note: images also need to be ported back by storing them in `File` (this is not part of this commit)

@vioia's FAQ changes ported back to Git

---

IAM/Frequently_asked_questions.mediawiki
Security/InfoSec.mediawiki

backport viorela's changes + infosec notification

---

IAM/Frequently_asked_questions.mediawiki

@hmitsch Any suggestions on this content?

Add Email FAQ question
